import { DEDUCTION_CATEGORIES, type DeductionRule } from "./types";

export const DEDUCTION_RULES: DeductionRule[] = [
  {
    id: "home-internet",
    category: DEDUCTION_CATEGORIES.HOME_OFFICE,
    keywords: [
      "internet",
      "wifi",
      "broadband",
      "comcast",
      "xfinity",
      "spectrum",
      "fios",
      "fiber",
      "verizon",
      "att",
    ],
    deductionPercent: 0.4,
    irsCategory: "IRS Schedule C - Home Office",
    baseConfidence: 0.55,
    requires: ["worksFromHome"],
  },
  {
    id: "home-utilities",
    category: DEDUCTION_CATEGORIES.HOME_OFFICE,
    keywords: [
      "utility",
      "utilities",
      "electric",
      "electricity",
      "gas",
      "water",
      "sewer",
      "energy",
      "pge",
      "coned",
    ],
    deductionPercent: 0.25,
    irsCategory: "IRS Schedule C - Home Office",
    baseConfidence: 0.5,
    requires: ["worksFromHome"],
  },
  {
    id: "home-rent",
    category: DEDUCTION_CATEGORIES.HOME_OFFICE,
    keywords: [
      "rent",
      "landlord",
      "apartment",
      "lease",
      "leasing",
      "property management",
    ],
    deductionPercent: 0.15,
    irsCategory: "IRS Schedule C - Home Office",
    baseConfidence: 0.5,
    requires: ["worksFromHome"],
  },
  {
    id: "travel-rideshare",
    category: DEDUCTION_CATEGORIES.BUSINESS_TRAVEL,
    keywords: ["uber", "lyft", "rideshare", "taxi", "cab"],
    deductionPercent: 1,
    irsCategory: "IRS Schedule C - Travel",
    baseConfidence: 0.6,
  },
  {
    id: "travel-airfare",
    category: DEDUCTION_CATEGORIES.BUSINESS_TRAVEL,
    keywords: [
      "airline",
      "airlines",
      "flight",
      "delta",
      "united",
      "american airlines",
      "southwest",
      "jetblue",
      "alaska",
    ],
    deductionPercent: 1,
    irsCategory: "IRS Schedule C - Travel",
    baseConfidence: 0.6,
  },
  {
    id: "travel-lodging",
    category: DEDUCTION_CATEGORIES.BUSINESS_TRAVEL,
    keywords: ["hotel", "inn", "marriott", "hilton", "hyatt", "airbnb"],
    deductionPercent: 1,
    irsCategory: "IRS Schedule C - Travel",
    baseConfidence: 0.55,
  },
  {
    id: "travel-parking",
    category: DEDUCTION_CATEGORIES.BUSINESS_TRAVEL,
    keywords: ["parking", "garage", "meter", "parkwhiz"],
    deductionPercent: 1,
    irsCategory: "IRS Schedule C - Travel",
    baseConfidence: 0.5,
  },
  {
    id: "office-supplies",
    category: DEDUCTION_CATEGORIES.OFFICE_SUPPLIES,
    keywords: ["amazon", "staples", "office depot", "officedepot", "officemax"],
    deductionPercent: 1,
    irsCategory: "IRS Schedule C - Supplies",
    baseConfidence: 0.5,
  },
  {
    id: "professional-books",
    category: DEDUCTION_CATEGORIES.PROFESSIONAL_DEVELOPMENT,
    keywords: ["book", "books", "kindle", "audible", "oreilly", "barnes"],
    deductionPercent: 1,
    irsCategory: "IRS Schedule C - Education",
    baseConfidence: 0.45,
  },
  {
    id: "professional-courses",
    category: DEDUCTION_CATEGORIES.PROFESSIONAL_DEVELOPMENT,
    keywords: ["course", "training", "udemy", "coursera", "pluralsight", "edx"],
    deductionPercent: 1,
    irsCategory: "IRS Schedule C - Education",
    baseConfidence: 0.45,
  },
  {
    id: "professional-conferences",
    category: DEDUCTION_CATEGORIES.PROFESSIONAL_DEVELOPMENT,
    keywords: ["conference", "summit", "expo", "webinar", "eventbrite", "meetup"],
    deductionPercent: 1,
    irsCategory: "IRS Schedule C - Education",
    baseConfidence: 0.45,
  },
  {
    id: "health-pharmacy",
    category: DEDUCTION_CATEGORIES.HEALTH,
    keywords: ["pharmacy", "cvs", "walgreens", "rite aid", "riteaid", "drugstore"],
    deductionPercent: 1,
    irsCategory: "IRS Schedule A - Medical Expenses",
    baseConfidence: 0.45,
  },
  {
    id: "health-medical",
    category: DEDUCTION_CATEGORIES.HEALTH,
    keywords: ["medical", "clinic", "hospital", "urgent care", "dental", "doctor"],
    deductionPercent: 1,
    irsCategory: "IRS Schedule A - Medical Expenses",
    baseConfidence: 0.45,
  },
  {
    id: "health-insurance",
    category: DEDUCTION_CATEGORIES.HEALTH,
    keywords: [
      "health insurance",
      "anthem",
      "aetna",
      "cigna",
      "blue cross",
      "blue shield",
      "kaiser",
    ],
    deductionPercent: 1,
    irsCategory: "IRS Schedule A - Medical Expenses",
    baseConfidence: 0.5,
  },
  {
    id: "charity-donations",
    category: DEDUCTION_CATEGORIES.CHARITY,
    keywords: [
      "donation",
      "donate",
      "charity",
      "goodwill",
      "salvation army",
      "red cross",
      "unicef",
      "church",
      "foundation",
    ],
    deductionPercent: 1,
    irsCategory: "IRS Schedule A - Charitable Contributions",
    baseConfidence: 0.5,
  },
];
